### ISSUE TITLE
Date Selection sets date 2 days back

### ISSUE THREAD

**Issue by sujoydc** [hamzahamidi/ajsf#154]
**Describe the bug**
which template:

* [ ] MaterialDesignFrameworkModule — Material Design

When you select a date it actually selects selected date - 2 days date.

**To Reproduce**

1. Select a date in date picket e.g.17th Oct. It will actually select 15th Oct. 
2. The data shows 16th Oct. Please see the screen shot.

**Desktop (please complete the following information):**

- OS: [e.g. Windows]
- Browser [chrome]

![image](https://user-images.githubusercontent.com/1069026/66771443-3eea0d80-ee88-11e9-8627-060e2a00376b.png)

**Comment by blained3** [comment]
Please fix this ASAP! I don't want to have to create a custom date component

**Comment by hamzahamidi** [comment]
Duplicate https://github.com/hamzahamidi/ajsf/pull/69

**Comment by hamzahamidi** [comment]
Linked to #69

**Comment by hamzahamidi** [comment]
Fix in #189

**Comment by hamzahamidi** [comment]
Fix available in online demo. Can someone check if it fixes the issue? @sujoydc @blained3

**Comment by stucker1992** [comment]
![image](https://user-images.githubusercontent.com/19466856/76210429-09114100-61fc-11ea-9b58-61aa1ac91436.png)

Looks good to me!

**Comment by blained3** [comment]
I still see this happening even on your demo page here: https://hamidihamza.com/ajsf/.
 
Steps to Reproduce:

1. Go to Demo 
2. Click the calendar icon for the date picker to bring up the calendar picker
3. Select a date by clicking on it (I clicked on today's date which is 3/9/2020)
4. After selecting, view the date that is on the form and notice the 2 day difference (My example displayed as 3/7/2020)

For context, I am in the Mountain Daylight Time Zone and it is 9:30 am.

**Comment by Krashlog** [comment]
So, just to be clear,this fix wasn't merged? Still having the issue right now.
